name: Validate with hassfest

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: "actions/checkout@v4"

      - name: Run Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
